2024-04-18 11:35:50,015 - test.py - [line:10] - INFO - Traceback (most recent call last):
  File "C:\Users\yangtuo\PycharmProjector\APITest\tools\test.py", line 8, in test
    1/0
    ~^~
ZeroDivisionError: division by zero

